package ru.samates.gardenspa.domain

/** Retail presence and manufacturer instructions checked separately on 2026-09-19.
 * Rows are crop/target/ground combinations, never a Cartesian expansion of a retail description. */
object LemanaProgramProducts {
    private val outdoor = setOf(CultivationType.OPEN_GROUND)
    private val greenhouse = setOf(CultivationType.GREENHOUSE)
    private val flowers = setOf("peony", "rose")
    private const val DISEASE_STORE = "https://ulyanovsk.lemanapro.ru/catalogue/zashchita-rasteniy-ot-bolezney/"
    private const val PEST_STORE = "https://ufa.lemanapro.ru/catalogue/zashchita-rasteniy-ot-bolezney/insekticidy-dlya-rasteniy/"
    private const val ALATAR = "https://www.vhoz.ru/catalog/tovary_dlya_sada_i_ogoroda/sredstva_zashchity_rasteniy_ot_vrediteley_/alatar-universalnyy-preparat-dlya-zashchity-ot-vrediteley/"
    private const val TRICHO = "https://www.vhoz.ru/catalog/tovary_dlya_sada_i_ogoroda/sredstva_zashchity_rasteniey_ot_bolezney/trikhoderma-veride-biopreparat-dlya-zashchity-rasteniy-ot-bolezney/"
    private const val ISKRA = "https://www.technoexport.ru/catalog/household/plant-protection/insect-pests/iskra-dvojnoj-effekt/"

    private fun treatment(id: String, name: String, maker: String, crops: Set<String>, problems: Set<String>,
        instruction: String, source: String, retail: String?, ground: Set<CultivationType> = outdoor,
        root: Boolean = false) = ProgramProduct(id, name, maker,
        if (root) "Пролить почву: $name" else "Применить: $name",
        "Для указанной культуры и цели; отдельная схема применения.", instruction, source, crops,
        problems, ground, sections = setOf(if (root) ProductSection.FERTILIZER else ProductSection.TREATMENT), retailUrl = retail)

    val products = listOf(
        treatment("batrider_potato", "Батрайдер, СК — картофель", "Август", setOf("potato"), setOf("colorado_beetle"),
            "1,5 мл/3 л; 3 л/100 м². Одна обработка, ожидание 20 дней. Содержит альфа-циперметрин, имидаклоприд и клотианидин.",
            "https://dacha.avgust.com/catalog/batrayder/", PEST_STORE),
        treatment("batrider_cucumber", "Батрайдер, СК — огурец в теплице", "Август", setOf("cucumber"), setOf("aphids", "thrips", "whitefly"),
            "5 мл/10 л; 10 л/100 м². Одна обработка, ожидание 3 дня.", "https://dacha.avgust.com/catalog/batrayder/", PEST_STORE, greenhouse),
        treatment("batrider_flowers", "Батрайдер, СК — цветы открытого грунта", "Август", flowers, setOf("aphids", "thrips"),
            "2 мл/3 л; 3 л/100 м². Одна обработка. Учитывать ограничения для пчёл на этикетке.", "https://dacha.avgust.com/catalog/batrayder/", PEST_STORE),
        treatment("batrider_hydrangea", "Батрайдер, СК — декоративные кустарники", "Август", setOf("hydrangea"), setOf("aphids", "thrips"),
            "2 мл/10 л; 0,5–1 л/куст. Одна обработка.", "https://dacha.avgust.com/catalog/batrayder/", PEST_STORE),
        treatment("batrider_apple", "Батрайдер, СК — яблоня", "Август", setOf("apple"), setOf("aphids", "weevil"),
            "2 мл/10 л; 1–5 л/дерево. Одна обработка от тли или яблонного цветоеда, ожидание 20 дней.", "https://dacha.avgust.com/catalog/batrayder/", PEST_STORE),
        treatment("bona_pyrethrum_flowers", "Натуральный спрей, пиретрины 0,04%, 500 мл", "BonaForte", flowers + "hydrangea", setOf("aphids", "thrips", "spider_mite"),
            "Готовый спрей: взболтать, наносить с расстояния от 20 см, включая нижнюю сторону листьев, без стекания. Вечером или в пасмурную погоду. Это контактное средство: предварительно проверить переносимость на части растения. Не разбавлять и не переносить нормы концентрата. Кратность уточните на упаковке.",
            "https://www.bona-forte.ru/catalog/naturalnyj-sprej-ot-letayushchikh-i-polzayushchikh-nasekomykh-500-ml/",
            "https://ufa.lemanapro.ru/product/sprey-insekticid-bona-forte-naturalnyy-500ml-82197958/"),
        treatment("aktara_potato", "Актара, ВДГ — картофель", "Syngenta", setOf("potato"), setOf("colorado_beetle"),
            "Тиаметоксам 250 г/кг, водно-диспергируемые гранулы. На 100 м²: 0,6 г препарата и 4 л воды. Одна обработка, ожидание 14 дней. Выход для ручных работ через 7 дней по каталогу 2025 года. Не переносить норму жидкой формы КС.",
            "https://www.syngenta.ru/sites/g/files/kgtney371/files/media/document/2024/11/11/catalog_2025.pdf", PEST_STORE),
        treatment("alatar_potato", "Алатар, КЭ — картофель", "Ваше хозяйство", setOf("potato"), setOf("colorado_beetle"),
            "5 мл/4 л; до 4 л/100 м². Ожидание 20 дней, одна обработка. Малатион и циперметрин.", ALATAR, PEST_STORE),
        treatment("alatar_strawberry", "Алатар, КЭ — земляника", "Ваше хозяйство", setOf("garden-strawberry"), setOf("weevil"),
            "5 мл/4 л; до 4 л/100 м². Ожидание 30 дней, одна обработка против малинно-земляничного долгоносика.", ALATAR, PEST_STORE),
        treatment("alatar_apple", "Алатар, КЭ — яблоня", "Ваше хозяйство", setOf("apple"), setOf("codling_moth", "weevil"),
            "5 мл/10 л; до 5 л/дерево. Ожидание 30 дней, максимум две обработки. Для цветоеда или плодожорки по этикетке.", ALATAR, PEST_STORE),
        treatment("alatar_currant", "Алатар, КЭ — смородина", "Ваше хозяйство", setOf("currant"), setOf("aphids"),
            "5 мл/5 л; до 1 л/куст. Ожидание 25 дней, одна обработка.", ALATAR, PEST_STORE),
        treatment("alatar_flowers", "Алатар, КЭ — цветы", "Ваше хозяйство", flowers, setOf("aphids", "thrips"),
            "5 мл/10 л; 1–2 л/10 м². Одна обработка. Применять в безветренную погоду утром или вечером; соблюдать ограничения для пчёл.", ALATAR, PEST_STORE),
        treatment("biotlin_greenhouse", "Биотлин, ВРК — томат и огурец в теплице", "Август", setOf("tomato", "cucumber"), setOf("aphids", "whitefly"),
            "Имидаклоприд 200 г/л. 5 мл/10 л; 10 л/100 м². Ожидание 3 дня, одна обработка.",
            "https://dacha.avgust.com/catalog/biotlin/", PEST_STORE, greenhouse),
        treatment("biotlin_apple", "Биотлин, ВРК — яблоня", "Август", setOf("apple"), setOf("aphids", "weevil"),
            "3 мл/10 л; 2–5 л/дерево. Ожидание 60 дней, одна обработка. От цветоеда — только до цветения.",
            "https://dacha.avgust.com/catalog/biotlin/", PEST_STORE),
        treatment("biotlin_currant", "Биотлин, ВРК — смородина", "Август", setOf("currant"), setOf("aphids"),
            "3 мл/10 л; 0,5–1,5 л/куст. Только до цветения, ожидание 60 дней, одна обработка.",
            "https://dacha.avgust.com/catalog/biotlin/", PEST_STORE),
        treatment("kleshchevit_greenhouse", "Клещевит, КЭ — овощи в теплице", "Август", setOf("tomato", "cucumber", "sweet-pepper", "eggplant"), setOf("spider_mite"),
            "Аверсектин С 2 г/л. 10 мл/1 л; до 10 л/100 м². Ожидание 3 дня, максимум три обработки. Это обычный Клещевит, не Клещевит Супер для территории.",
            "https://dacha.avgust.com/catalog/kleshchevit/", PEST_STORE, greenhouse),
        treatment("kleshchevit_currant", "Клещевит, КЭ — смородина", "Август", setOf("currant"), setOf("spider_mite"),
            "2 мл/1 л; до 1 л/куст. Ожидание 3 дня, максимум две обработки.", "https://dacha.avgust.com/catalog/kleshchevit/", PEST_STORE),
        treatment("kleshchevit_apple", "Клещевит, КЭ — яблоня", "Август", setOf("apple"), setOf("spider_mite"),
            "1,5 мл/1 л; до 5 л/дерево. Ожидание 3 дня, максимум две обработки.", "https://dacha.avgust.com/catalog/kleshchevit/", PEST_STORE),
        treatment("kleshchevit_flowers", "Клещевит, КЭ — цветы открытого грунта", "Август", flowers, setOf("spider_mite"),
            "2 мл/1 л; до 10 л/100 м². Максимум четыре обработки.", "https://dacha.avgust.com/catalog/kleshchevit/", PEST_STORE),
        treatment("topaz_currant", "Топаз, КЭ — смородина", "Syngenta", setOf("currant"), setOf("powdery_mildew"),
            "Пенконазол 100 г/л. 2 мл/10 л; 10 л/100 м². При первых признаках; ожидание 14 дней, максимум четыре обработки.",
            "https://dacha.avgust.com/catalog/topaz/", DISEASE_STORE),
        treatment("topaz_flowers", "Топаз, КЭ — цветы", "Syngenta", flowers, setOf("powdery_mildew", "rust"),
            "4 мл/10 л; 10 л/100 м². Одна обработка в период вегетации. Не переносить норму для смородины.",
            "https://dacha.avgust.com/catalog/topaz/", DISEASE_STORE),
        treatment("skor_fruit", "Скор, КЭ — яблоня и груша", "Syngenta", setOf("apple", "pear"), setOf("scab", "powdery_mildew"),
            "Дифеноконазол 250 г/л. 2 мл/10 л; 2–5 л/дерево. До и после цветения, интервал не более 14 дней. Ожидание 20 дней, максимум три обработки.",
            "https://dacha.avgust.com/catalog/skor/", DISEASE_STORE),
        treatment("skor_peony", "Скор, КЭ — пион", "Syngenta", setOf("peony"), setOf("powdery_mildew", "gray_mold"),
            "Мучнистая роса: 2 мл/10 л; серая гниль: 4 мл/10 л. 10 л/100 м², максимум две обработки через 14 дней.",
            "https://dacha.avgust.com/catalog/skor/", DISEASE_STORE),
        treatment("skor_rose", "Скор, КЭ — роза", "Syngenta", setOf("rose"), setOf("powdery_mildew", "leaf_spot"),
            "Мучнистая роса: 2 мл/10 л, максимум дважды. Чёрная пятнистость: 5 мл/10 л, максимум четырежды. 10 л/100 м², до 1 л/растение; интервал 14 дней. Для других пятнистостей уточнить диагноз.",
            "https://dacha.avgust.com/catalog/skor/", DISEASE_STORE),
        treatment("skor_hydrangea", "Скор, КЭ — декоративные кустарники", "Syngenta", setOf("hydrangea"), setOf("powdery_mildew", "leaf_spot"),
            "Мучнистая роса: 2 мл/10 л, максимум дважды; пятнистости: 5 мл/10 л, максимум четырежды. 10 л/100 м²; интервал 14 дней.",
            "https://dacha.avgust.com/catalog/skor/", DISEASE_STORE),
        treatment("tricho_tomato_leaf", "Триходерма вериде — томат открытого грунта", "Ваше хозяйство", setOf("tomato"), setOf("late_blight", "alternaria"),
            "Штамм 471. 30 г/10 л; 10 л/100 м², от бутонизации до плодоношения. Кратность 1–2; по карточке без срока ожидания.", TRICHO, DISEASE_STORE),
        treatment("tricho_cucumber_leaf", "Триходерма вериде — огурец открытого грунта", "Ваше хозяйство", setOf("cucumber"), setOf("downy_mildew"),
            "30 г/10 л; 10 л/100 м², от начала цветения до плодоношения. Кратность 1–2; без срока ожидания по карточке.", TRICHO, DISEASE_STORE),
        treatment("tricho_tomato_gray", "Триходерма вериде — томат в теплице", "Ваше хозяйство", setOf("tomato"), setOf("gray_mold"),
            "15 г/10 л; 10 л/50 м², от бутонизации до плодоношения. Кратность 1–2; без срока ожидания по карточке.", TRICHO, DISEASE_STORE, greenhouse),
        treatment("tricho_root_outdoor", "Триходерма вериде — корневой полив овощей", "Ваше хозяйство", setOf("tomato", "cucumber"), setOf("root_rot"),
            "30 г/10 л; 100–200 мл/растение. Томат: 2–5 листьев, огурец: 2–4; повтор через две недели. Без срока ожидания по карточке.", TRICHO, DISEASE_STORE, root = true),
        treatment("tricho_root_greenhouse", "Триходерма вериде — корневой полив в теплице", "Ваше хозяйство", setOf("tomato", "cucumber"), setOf("root_rot"),
            "30 г/10 л; 100–200 мл/растение при посадке и через 2–3 недели. Две обработки; без срока ожидания по карточке.", TRICHO, DISEASE_STORE, greenhouse, root = true),
        treatment("iskra_fruit", "Искра Двойной эффект, ТАБ — плодовые", "Green Belt", setOf("apple", "pear"), setOf("aphids", "codling_moth"),
            "Таблетка 10 г на 10 л; 10 л на 1–5 деревьев по возрасту. Срок ожидания, предельную кратность и допуск своей фасовки проверьте на этикетке до назначения.", ISKRA, PEST_STORE),
        treatment("iskra_weevil", "Искра Двойной эффект, ТАБ — долгоносик земляники", "Green Belt", setOf("garden-strawberry"), setOf("weevil"),
            "10 г/10 л; 1,5 л/10 м². Срок ожидания и кратность — по этикетке; при близком сборе без подтверждённого срока не применять.", ISKRA, PEST_STORE),
        treatment("iskra_potato", "Искра Двойной эффект, ТАБ — картофель", "Green Belt", setOf("potato"), setOf("colorado_beetle"),
            "10 г/10 л; 10 л/100 м². Срок ожидания и кратность проверить на этикетке. Циперметрин 21 г/кг и перметрин 9 г/кг.", ISKRA, PEST_STORE),
        treatment("iskra_flowers", "Искра Двойной эффект, ТАБ — цветы и декоративные", "Green Belt", flowers + "hydrangea", setOf("aphids", "thrips"),
            "10 г/10 л; до 2 л/10 м². Кратность и ограничения для пчёл проверить на этикетке.", ISKRA, PEST_STORE),
        treatment("sporobacterin_vegetables", "Споробактерин, 20 г — овощные культуры", "Ортон", setOf("tomato", "cucumber", "sweet-pepper", "eggplant", "cabbage"),
            setOf("powdery_mildew", "late_blight", "downy_mildew"),
            "Bacillus subtilis и Trichoderma viride. Для опрыскивания: 20 г/20 л, 10 л/100 м²; при первых признаках болезни, две обработки через 2–3 недели. Подготовка раствора и соответствующая культуре строка — в инструкции. Это частичная альтернатива Биозащитину по защите от болезней; от вредителей не заменяет.",
            "https://orton.ru/catalog/sredstva_zashchity_rasteniy/fungitsidnye_sredstva/sporobakterin/", null,
            CultivationType.entries.toSet())
    )
}
